name: escort
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  image_picker: ^1.0.4
  video_player: ^2.8.1
  # google_fonts: ^6.1.0
  flutter:
    sdk: flutter
   

 #utility Packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  go_router: ^14.2.3
  flutter_secure_storage: ^9.0.0 
  json_annotation: ^4.8.1
  

#icons
  iconsax: ^0.0.8 
  cupertino_icons: ^1.0.8
  flutter_vector_icons: ^2.0.0
  google_fonts: ^6.1.0

  # google_fonts: ^5.1.0
#state management
  get: ^4.6.5
  get_storage: ^2.1.1 
  timeago: ^3.7.1
  geolocator: ^14.0.2
  google_maps_flutter: ^2.12.3
  shared_preferences: ^2.5.3

#product Specific


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true



assets:
  -lib/assets/
  


fonts:
    -family: Poppins
    fonts:
        - asset: assets/fonts/Poppins-light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-semiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800