name: escort
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  flutter_localized_locales: ^2.0.5
  image_picker: ^1.0.4
  video_player: ^2.8.1
  webview_flutter: ^4.0.0
  webview_flutter_wkwebview: ^3.9.4
  webview_flutter_android: ^3.12.1
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  flutter_local_notifications: ^16.3.0
  record: ^5.0.4
  audioplayers: ^5.2.1
  file_picker: ^10.3.3
 #utility Packages
  http: ^1.2.2
  intl: ^0.20.2
  logger: ^2.0.1
  url_launcher: ^6.1.12
  go_router: ^14.2.3
  flutter_secure_storage: ^9.0.0 
  json_annotation: ^4.8.1
  cached_network_image: ^3.3.1
  http_parser: ^4.0.2
  mime: ^1.0.4
  path_provider: ^2.1.2

#icons
  iconsax: ^0.0.8 
  cupertino_icons: ^1.0.8
  flutter_vector_icons: ^2.0.0
  google_fonts: ^6.1.0

  # google_fonts: ^5.1.0
#state management
  get: ^4.6.5
  get_storage: ^2.1.1 
  provider: ^6.1.2
  timeago: ^3.7.1
  geolocator: ^14.0.2
  google_maps_flutter: ^2.12.3
  shared_preferences: ^2.5.3
  image_cropper: ^9.1.0
  socket_io_client: ^2.0.3+1

#product Specific


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true



assets:
  -lib/assets/
  


fonts:
    -family: Poppins
    fonts:
        - asset: assets/fonts/Poppins-light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-semiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
